name: Instagram Scheduler - INK_WISPS

on:
  schedule:
    - cron: "*/45 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  post_INK_WISPS:
    runs-on: ubuntu-latest
    env:
      IG_INK_WISPS_TOKEN: ${{ secrets.IG_INK_WISPS_TOKEN }}
      IG_INK_WISPS_ID: ${{ secrets.IG_INK_WISPS_ID }}
      DROPBOX_INK_WISPS_REFRESH: ${{ secrets.DROPBOX_INK_WISPS_REFRESH }}
      DROPBOX_INK_WISPS_APP_KEY: ${{ secrets.DROPBOX_INK_WISPS_APP_KEY }}
      DROPBOX_INK_WISPS_APP_SECRET: ${{ secrets.DROPBOX_INK_WISPS_APP_SECRET }}
      GH_PAT: ${{ secrets.GH_PAT }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install dropbox requests python-telegram-bot==13.15 pynacl

      - name: Run INK_WISPS Posting Script
        run: python ink_wisps_post.py
