name: Instagram Scheduler - Inkwisps

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  post_inkwisps:
    runs-on: ubuntu-latest
    env:
      IG_INKWISPS_TOKEN: ${{ secrets.IG_INKWISPS_TOKEN }}
      IG_INKWISPS_ID: ${{ secrets.IG_INKWISPS_ID }}
      DROPBOX_INKWISPS_REFRESH: ${{ secrets.DROPBOX_INKWISPS_REFRESH }}
      DROPBOX_INKWISPS_APP_KEY: ${{ secrets.DROPBOX_INKWISPS_APP_KEY }}
      DROPBOX_INKWISPS_APP_SECRET: ${{ secrets.DROPBOX_INKWISPS_APP_SECRET }}
      GH_PAT: ${{ secrets.GH_PAT }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install dropbox requests python-telegram-bot==13.15 pynacl

      - name: Run Inkwisps Posting Script
        run: python inkwisps_post.py
