name: Telegram Bot Scheduler (Every 3 hours)

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 16  # Auto-kill if unresponsive

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_BOT_PASSWORD: ${{ secrets.TELEGRAM_BOT_PASSWORD }}  # ✅ Add this
      GH_PAT: ${{ secrets.GH_PAT }}  # ✅ Required for GitHub secret updates
      GITHUB_REPOSITORY: ${{ github.repository }}  # ✅ Required by script for GitHub API

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot==13.7 dropbox pynacl requests

      - name: Start Telegram Bot
        run: python telegram_bot_controller.py
