name: Telegram Bot Scheduler (Every 3 hours)

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 16  # Auto-kills if something fails

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot==13.7 dropbox pynacl requests

      - name: Start Telegram Bot
        run: python telegram_bot_controller.py
